OFED 5.9-0.5.6.0

diff --git a/ofed_scripts/configure b/ofed_scripts/configure
--- a/ofed_scripts/configure
+++ b/ofed_scripts/configure
@@ -174,9 +174,6 @@ Usage:  `basename $0` [options]
     --with-sf-cfg-drv    make CONFIG_MLX5_SF_CFG=y [no]
     ----without-sf-cfg-drv    [yes]
 
-    --with-mlx5-macsec             make  CONFIG_MLX5_EN_MACSEC=y [no]
-    --without-mlx5-macsec          [yes]
-
 EOF
 
 #   Currently not supported options
@@ -254,6 +251,22 @@ unset_complex_define_to_config_h()
 	echo "/* #undef $1 */" >> $COMPAT_CONFIG_H
 }
 
+set_config_mk_kernel()
+{
+	echo "Complex config: Set $1 to y in ${CWD}/${CONFIG}"
+	echo "Complex config: Set $1 to 1 in ${AUTOCONF_H}"
+	echo "$1=y" >> ${CWD}/${CONFIG}
+	echo "#define $1 1" >> ${AUTOCONF_H}
+}
+
+unset_config_mk_kernel()
+{
+	echo "Complex config: Unset $1 in ${CWD}/${CONFIG}"
+	echo "Complex config: Unset $1 in ${AUTOCONF_H}"
+	echo "$1=" >> ${CWD}/${CONFIG}
+	echo "#undef $1" >> ${AUTOCONF_H}
+}
+
 # We are resolving some features availability
 # by combining few defines generated by autogen.sh
 # extracted from compat/config.h
@@ -264,6 +277,26 @@ check_complex_defines()
         echo " * based on defines prior this section" >> $COMPAT_CONFIG_H
 
         echo " *  _________________________________________________________ */" >> $COMPAT_CONFIG_H
+
+#define REBASE_STAGE REBASE_STAGE_UPSTREAM/REBASE_STAGE_BASE/REBASE_STAGE_BACKPORTS
+	if [ "$REBASE_STAGE" = "UPSTREAM" ]; then
+		set_complex_define_to_config_h REBASE_STAGE_UPSTREAM
+	elif [ "$REBASE_STAGE" = "BASE" ]; then
+		set_complex_define_to_config_h REBASE_STAGE_BASE
+	else
+		set_complex_define_to_config_h REBASE_STAGE_BACKPORTS
+	fi
+
+# Define HAVE_BASECODE_EXTRAS always set define.
+# Use to wrap extra code added to base code with backports apply.
+# This wrapped code compile over all kernels.
+        if [ "X${CONFIG_ENABLE_BASECODE_EXTRAS}" == "Xy" ]
+	then
+		set_complex_define_to_config_h HAVE_BASECODE_EXTRAS
+	else
+		unset_complex_define_to_config_h HAVE_BASECODE_EXTRAS
+	fi
+
 # Define HAVE_TC_SETUP_FLOW_ACTION from other flags
 	if check_compat_config_h_var HAVE_TC_SETUP_FLOW_ACTION_FUNC ||
 	   check_compat_config_h_var HAVE_TC_SETUP_OFFLOAD_ACTION_FUNC ||
@@ -458,12 +491,15 @@ check_complex_defines()
 		unset_complex_define_to_config_h HAVE_IS_PCI_P2PDMA_PAGE
 	fi
 
+# Define CONFIG_MLX5_EN_MACSEC based on kernel config and HAVE_
 	check_autofconf CONFIG_MACSEC
-	if [ "X${CONFIG_MLX5_EN_MACSEC}" == "Xy" ]; then
+	if [ "${CONFIG_MACSEC}" == "1" ]; then
 	    if check_compat_config_h_var HAVE_STRUCT_MACSEC_INFO_METADATA; then
 			CONFIG_MLX5_EN_MACSEC="y"
+			set_config_mk_kernel CONFIG_MLX5_EN_MACSEC
 		else
 			CONFIG_MLX5_EN_MACSEC=
+			unset_config_mk_kernel CONFIG_MLX5_EN_MACSEC
 	    fi
 	fi
 
@@ -485,11 +521,16 @@ check_complex_defines()
 		unset_complex_define_to_config_h HAVE_BLK_TYPES_REQ_OP_DRV_OUT
 	fi
 
+# Define HAVE_NO_REFCNT_BIAS to be set off default until refcnt_bias member
+# of struct alloc_unit is removed.
+
+	unset_complex_define_to_config_h HAVE_NO_REFCNT_BIAS
+
 }
 
-check_kerver_rh()
+check_kerver_rh_cls()
 {
-	perl -e '($v, $r) = split "-", "'$1'"; exit($v eq "3.10.0" && $r >= 1062 ? 0 : 1)'
+	perl -e '($v, $r) = split "-", "'$1'"; exit($v eq "3.10.0" && $r >= 693 ? 0 : 1)'
 }
 
 check_kerver_rh_bridge()
@@ -683,11 +724,15 @@ CONFIG_GPU_DIRECT_STORAGE=${CONFIG_GPU_DIRECT_STORAGE:-''}
 
 CONFIG_ENABLE_MLX5_FS_DEBUGFS=${CONFIG_ENABLE_MLX5_FS_DEBUGFS:-''}
 CONFIG_ENABLE_XDP="y"
+CONFIG_ENABLE_BASECODE_EXTRAS="y"
 
 # should be unset once backport finished 
 # block RHEL supports
-OFED_BASE_KVERSION="5.17.0"
+OFED_BASE_KVERSION="6.0"
 MIN_KVERSION="3.10"
+
+# Rebase stage UPSTREAM/BASE/BACKPORTS
+REBASE_STAGE="BACKPORTS"
 
 # nfs-rdma
 NFSRDMA_SUPPORTED_KVERSION="4.12.0"
@@ -715,7 +760,6 @@ AUXBUS_NON_SUPPORTED_KVERSION_AND_ABOVE="6.2"
 
 # cls_act
 CLS_ACT_SUPPORTED_KVERSION="4.12.0"
-CLS_ACT_SUPPORTED_KVERSION_LIST="3.10.0-693 3.10.0-862 3.10.0-957 3.10.0-1062 3.10.0-1127"
 CLS_ACT_NON_SUPPORTED_KVERSION_AND_ABOVE="6.2"
 
 # bridge offload
@@ -1412,6 +1456,9 @@ main()
                         --without-xdp)
 			CONFIG_ENABLE_XDP=
                         ;;
+                        --without-basecode-extras)
+			CONFIG_ENABLE_BASECODE_EXTRAS=
+                        ;;
                         --with-mlxdevm-mod)
                         CONFIG_MLXDEVM="m"
                         ;;
@@ -1423,12 +1470,6 @@ main()
                         ;;
                         --without-sf-cfg-drv)
                         CONFIG_MLX5_SF_CFG=
-                        ;;
-			--with-mlx5-macsec)
-                            CONFIG_MLX5_EN_MACSEC="y"
-                        ;;
-			--without-mlx5-macsec)
-                            CONFIG_MLX5_EN_MACSEC=
                         ;;
                     -h | --help)
                                 usage
@@ -1500,15 +1541,13 @@ if  check_kerver ${KVERSION} ${SWITCH_NON_SUPPORTED_KVERSION_AND_ABOVE}; then
 fi
 
 if ! check_kerver ${KVERSION} ${CLS_ACT_SUPPORTED_KVERSION}; then
-	if (! check_kerver_rh ${KVERSION}) || support_only_base ${CLS_ACT_SUPPORTED_KVERSION}; then
-		if ! check_kerver_list $KVERSION $CLS_ACT_SUPPORTED_KVERSION_LIST; then
+		if (! check_kerver_rh_cls ${KVERSION}) || support_only_base ${CLS_ACT_SUPPORTED_KVERSION}; then
 			CONFIG_MLX5_CLS_ACT=
 			CONFIG_MLX5_TC_CT=
 			CONFIG_MLX5_TC_SAMPLE=
 			CONFIG_MLX5_SW_STEERING=
 			echo "Warning: CONFIG_MLX5_CLS_ACT requires kernel version ${CLS_ACT_SUPPORTED_KVERSION} or higher (current: ${KVERSION})."
 		fi
-	fi
 fi
 
 if ! check_kerver ${KVERSION} ${BRIDGE_SUPPORTED_KVERSION}; then
@@ -1613,7 +1652,7 @@ if  check_kerver ${KVERSION} ${SRP_NON_SUPPORTED_KVERSION_AND_ABOVE}; then
 	echo "Warning: SRP not support kernel version ${SRP_NON_SUPPORTED_KVERSION_AND_ABOVE} or higher (current: ${KVERSION})."
 fi
 
-if ! check_kerver ${KVERSION} $SRP_SUPPORTED_KVERSION}; then
+if ! check_kerver ${KVERSION} $SRP_SUPPORTED_KVERSION; then
 	CONFIG_INFINIBAND_SRP=
 	CONFIG_SCSI_SRP_ATTRS=
 	echo "Warning: SRP requires kernel version ${SRP_SUPPORTED_KVERSION} or higher (current: ${KVERSION})."
@@ -1670,6 +1709,7 @@ esac
 #
 ################### disable/enable features/modules  ###########################
 #
+
 check_autofconf CONFIG_MMU_NOTIFIER
 if ! check_kerver ${KVERSION} ${ODP_SUPPORTED_KVERSION} || [ "X${CONFIG_MMU_NOTIFIER}" != "X1" ]; then
 	CONFIG_INFINIBAND_ON_DEMAND_PAGING=
@@ -1724,6 +1764,7 @@ fi
 if ! check_kerver ${KVERSION} ${MLXDEVM_SUPPORTED_KVERSION}; then
 	CONFIG_MLXDEVM=
 	CONFIG_MLX5_SF_CFG=
+	CONFIG_MLX5_SF=
 fi
 
 # if SF driver is not configured disable its configuration driver as well
@@ -1734,6 +1775,7 @@ fi
 check_autofconf CONFIG_NF_FLOW_TABLE
 if [ "${CONFIG_NF_FLOW_TABLE}" != "1" ]; then
 	CONFIG_MLX5_TC_CT=
+	echo "Warning: CONFIG_MLX5_TC_CT not supported in kernel once CONFIG_NF_FLOW_TABLE not set."
 fi
 #
 # Dummy modules for ULPs and storage:
@@ -1808,15 +1850,15 @@ check_autofconf CONFIG_INET6_ESP_OFFLOAD
 if [ "X${CONFIG_MLX5_EN_IPSEC}" == "Xy" ]; then
     ipsec_err=0
     if ! [ "X${CONFIG_XFRM_OFFLOAD}" == "X1" ]; then
-        echo "Warning: Innova IPsec requires CONFIG_XFRM_OFFLOAD to be enabled in kernel configuration."
+        echo "Warning: ConnectX IPsec requires CONFIG_XFRM_OFFLOAD to be enabled in kernel configuration."
         ipsec_err=1
     fi
     if ! [ "X${CONFIG_INET_ESP_OFFLOAD}" == "X1" ] && ! [ "X${CONFIG_INET6_ESP_OFFLOAD}" == "X1" ]; then
-        echo "Warning: Innova IPsec requires one of CONFIG_INET6_ESP_OFFLOAD or CONFIG_INET_ESP_OFFLOAD to be enabled in kernel configuration."
+        echo "Warning: ConnectX IPsec requires one of CONFIG_INET6_ESP_OFFLOAD or CONFIG_INET_ESP_OFFLOAD to be enabled in kernel configuration."
         ipsec_err=1
     fi
     if [ $ipsec_err -eq 1 ]; then
-        echo "Warning: Cannot build with Innova/ConnectX IPsec support. Exiting..."
+        echo "Warning: Cannot build with ConnectX IPsec support. Exiting..."
         CONFIG_MLX5_EN_IPSEC=
 	CONFIG_MLX5_IPSEC=
     fi
