OFED 5.1-0.6.6.0

diff --git a/ofed_scripts/mlnx_bf_configure b/ofed_scripts/mlnx_bf_configure
--- a/ofed_scripts/mlnx_bf_configure
+++ b/ofed_scripts/mlnx_bf_configure
@@ -44,52 +44,78 @@ if [ $$ -ne $PID ] ; then
         exit 0
 fi
 
-for dev in `lspci -n -d 15b3:a2d2 | cut -d ' ' -f 1`
+get_steering_mode()
+{
+	pci_dev=$1
+	shift
+
+	cat /sys/bus/pci/devices/${pci_dev}/net/*/compat/devlink/steering_mode 2> /dev/null
+}
+
+set_steering_mode()
+{
+	pci_dev=$1
+	mode=$2
+	shift 2
+
+	# devlink dev param set pci/${pci_dev} name flow_steering_mode value "${mode}" cmode runtime
+	echo ${mode} > /sys/bus/pci/devices/${pci_dev}/net/*/compat/devlink/steering_mode
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		logger -t $prog -i "Failed to configure steering mode ${mode} for ${pci_dev}"
+	else
+		logger -t $prog -i "Configured mode steering ${mode} for ${pci_dev}"
+	fi
+
+	return $rc
+}
+
+get_eswitch_mode()
+{
+	pci_dev=$1
+	shift
+
+	devlink dev eswitch show pci/${pci_dev} 2> /dev/null | cut -d ' ' -f 3
+}
+
+set_eswitch_mode()
+{
+	pci_dev=$1
+	mode=$2
+	shift 2
+
+	devlink dev eswitch set pci/${pci_dev} mode ${mode}
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		logger -t $prog -i "Failed to configure ${mode} mode for ${pci_dev}"
+	else
+		logger -t $prog -i "Configured ${mode} mode for ${pci_dev}"
+	fi
+
+	return $rc
+}
+
+for dev in `lspci -nD -d 15b3: | grep 'a2d[26]' | cut -d ' ' -f 1`
 do
 	if (mstconfig -d ${dev} q 2> /dev/null | grep -q "ECPF_ESWITCH_MANAGER.*ECPF(1)"); then
-		# Make sure the device is in legacy mode before configuring SW steering
-		devlink dev eswitch set pci/0000:${dev} mode legacy
-		# devlink dev param set pci/0000:${dev} name flow_steering_mode value "smfs" cmode runtime || \
-		echo smfs > /sys/bus/pci/devices/0000:${dev}/net/*/compat/devlink/steering_mode
-		rc=$?
-		if [ $rc -ne 0 ]; then
-			logger -t $prog -i "Failed to configure Software Steering for ${dev}"
-			RC=$((RC+rc))
-		else
-			logger -t $prog -i "Configured Software Steering for ${dev}"
-		fi
-		if ! (devlink dev eswitch show pci/0000:${dev} 2> /dev/null | grep -wq switchdev); then
-			devlink dev eswitch set pci/0000:${dev} mode switchdev
-			rc=$?
-			if [ $rc -ne 0 ]; then
-				logger -t $prog -i "Failed to configure switchdev mode for ${dev}"
-				RC=$((RC+rc))
-			else
-				logger -t $prog -i "Configured switchdev mode for ${dev}"
+		steering_mode=`get_steering_mode ${dev}`
+		if [ "${steering_mode}" == "dmfs" ]; then
+			eswitch_mode=`get_eswitch_mode ${dev}`
+			if [ "${eswitch_mode}" == "switchdev" ]; then
+				set_eswitch_mode ${dev} legacy
+				RC=$((RC+$?))
 			fi
+
+			set_steering_mode ${dev} smfs
+			RC=$((RC+$?))
+		fi
+		eswitch_mode=`get_eswitch_mode ${dev}`
+		if [ "${eswitch_mode}" != "switchdev" ]; then
+			set_eswitch_mode ${dev} switchdev
+			RC=$((RC+$?))
 		fi
 	fi
 done
-
-if [ $RC -eq 0 ]; then
-    cpus=`nproc`
-    max_active_miniflows=4
-    if [ $cpus -eq 8 ] ; then
-        miniflow_mask=f0
-        channels_cpu="0-3"
-    else
-        miniflow_mask=ff00
-        channels_cpu="0-7"
-    fi
-
-    echo $max_active_miniflows > /sys/bus/workqueue/devices/miniflow/max_active
-    echo $miniflow_mask > /sys/bus/workqueue/devices/miniflow/cpumask
-
-    set_irq_affinity_cpulist.sh $channels_cpu p0 > /dev/null
-    set_irq_affinity_cpulist.sh $channels_cpu p1 > /dev/null
-
-    logger -t $prog -i "SMFS performance tuning. Active miniflows: $max_active_miniflows miniflow cpumask: $miniflow_mask channels using cpus: $channels_cpu"
-fi
 
 if [ -f /etc/mellanox/mlnx-sf.conf ]; then
 	. /etc/mellanox/mlnx-sf.conf
