OFED 5.3-1.0.0.1

diff --git a/ofed_scripts/mlnx_bf_configure b/ofed_scripts/mlnx_bf_configure
--- a/ofed_scripts/mlnx_bf_configure
+++ b/ofed_scripts/mlnx_bf_configure
@@ -27,7 +27,8 @@
 # notice, one of the license notices in the documentation
 # and/or other materials provided with the distribution.
 
-PATH=/opt/mellanox/iproute2/sbin:/bin:/sbin:/usr/bin:/usr/sbin
+PATH=/opt/mellanox/iproute2/sbin:/opt/mellanox/ethtool/sbin:/bin:/sbin:/usr/bin:/usr/sbin
+CT_MAX_OFFLOADED_CONNS=1000000
 
 RC=0
 
@@ -114,6 +115,40 @@ set_eswitch_mode()
 	return $rc
 }
 
+set_ct_max_offloaded_conns()
+{
+	pci_dev=$1
+	max=$2
+	shift 2
+
+	devlink dev param set pci/${pci_dev} name ct_max_offloaded_conns value $max cmode runtime
+
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		error "Failed to configure devlink param ct_max_offloaded_conns=${max} for ${pci_dev}"
+	else
+		info "Configured devlink param ct_max_offloaded_conns=${max} for ${pci_dev}"
+	fi
+
+	return $rc
+}
+
+enable_shared_rq_feature()
+{
+	pci_dev=$1
+	shift 1
+
+	devlink dev param set pci/${pci_dev} name esw_pet_insert value true cmode runtime
+	rc=$?
+	if [ $rc -ne 0 ]; then
+		info "Shared RQ feature not supported"
+	else
+		info "Shared RQ feature enabled"
+	fi
+
+	return 0;
+}
+
 is_SecureBoot=0
 if (mokutil --sb-state 2>&1 | grep -q "SecureBoot enabled"); then
 	is_SecureBoot=1
@@ -130,6 +165,11 @@ mftconfig=mstconfig
 if [ -x /usr/bin/mlxconfig ]; then
 	mftconfig=mlxconfig
 fi
+
+if [ -f /etc/mellanox/mlnx-bf.conf ]; then
+	. /etc/mellanox/mlnx-bf.conf
+fi
+ALLOW_SHARED_RQ=${ALLOW_SHARED_RQ:-"yes"}
 
 num_of_devs=0
 for dev in `lspci -nD -d 15b3: | grep 'a2d[26]' | cut -d ' ' -f 1`
@@ -153,7 +193,13 @@ do
 		fi
 		eswitch_mode=`get_eswitch_mode ${dev}`
 		if [ "${eswitch_mode}" != "switchdev" ]; then
+			if [ "X${ALLOW_SHARED_RQ}" == "Xyes" ]; then
+				enable_shared_rq_feature ${dev}
+			fi
 			set_eswitch_mode ${dev} switchdev
+			RC=$((RC+$?))
+
+			set_ct_max_offloaded_conns ${dev} ${CT_MAX_OFFLOADED_CONNS}
 			RC=$((RC+$?))
 		fi
 		eswitch_mode=`get_eswitch_mode ${dev}`
@@ -164,6 +210,7 @@ do
 done
 
 if [ $RC -ne 0 ]; then
+	error "Exiting due to failures. RC=$RC"
 	exit $RC
 fi
 
@@ -181,11 +228,6 @@ if [ -f /etc/mellanox/mlnx-ovs.conf ]; then
 	. /etc/mellanox/mlnx-ovs.conf
 fi
 
-CREATE_OVS_BRIDGES=${CREATE_OVS_BRIDGES:-"yes"}
-if [ "X${CREATE_OVS_BRIDGES}" != "Xyes" ]; then
-	exit $RC
-fi
-
 vsctl=`which ovs-vsctl 2> /dev/null`
 if [ ! -n "$vsctl" ]; then
 	echo "OVS is not installed"
@@ -197,86 +239,117 @@ OVS_BRIDGE1_PORTS=${OVS_BRIDGE1_PORTS:-"p0 pf0hpf pf0sf0"}
 OVS_BRIDGE2=${OVS_BRIDGE2:-"ovsbr2"}
 OVS_BRIDGE2_PORTS=${OVS_BRIDGE2_PORTS:-"p1 pf1hpf pf1sf0"}
 OVS_HW_OFFLOAD=${OVS_HW_OFFLOAD:-"yes"}
-OVS_START_TIMEOUT=${OVS_START_TIMEOUT:-30}
 
+ovs_service=`systemctl list-units 2> /dev/null | grep openvswitch | awk '{print $1}'`
+
+if ! (systemctl is-enabled $ovs_service 2> /dev/null | grep -wq enabled); then
+	# OVS service is not enabled
+	info "$ovs_service is not enabled. Exiting..."
+	exit 0
+fi
+
+if [ "$ovs_service" == "openvswitch-switch.service" ]; then
+	ovs_start="/etc/init.d/openvswitch-switch start"
+	ovs_restart="/etc/init.d/openvswitch-switch restart"
+else
+	ovs_start=""
+	ovs_restart="systemctl restart $ovs_service"
+fi
+
+ovs_restart()
 {
-	i=0
-	while ! ($vsctl show > /dev/null 2>&1)
-	do
-		if [ $i -ge $OVS_START_TIMEOUT ]; then
-			break
-		fi
-		sleep 1
-		i=$((i+1))
-	done
-
-	if ! ($vsctl show > /dev/null 2>&1); then
-		# OVS service is not running
-		ovs_service=`systemctl list-units 2> /dev/null | grep openvswitch | awk '{print $1}'`
-		if [ -n "$ovs_service" ]; then
-			systemctl restart $ovs_service 2> /dev/null
-		fi
-
-		if ! ($vsctl show > /dev/null 2>&1); then
-			error "openvswitch service is not running"
-			RC=$((RC+$?))
-			exit $RC
-		fi
+	if [ -n "$ovs_service" ]; then
+		info "Restarting $ovs_service"
+		$ovs_restart
 	fi
 
-	for i in `seq $num_of_devs`
+	# Re-apply udev settings removed by OVS
+	if [ -x /lib/udev/mlnx_bf_udev ]; then
+		for p in $(cd /sys/class/net; /bin/ls -d p*)
+		do
+			/lib/udev/mlnx_bf_udev $p > /dev/null 2>&1
+		done
+	fi
+
+	for p in $OVS_BRIDGE1_PORTS $OVS_BRIDGE2_PORTS
 	do
-		br_name=OVS_BRIDGE${i}
-		br_name=${!br_name}
-		br_ports=OVS_BRIDGE${i}_PORTS
-		br_ports=${!br_ports}
+		ethtool -K $p hw-tc-offload on
+	done
+}
 
-		if ($vsctl br-exists $br_name); then
-			info "bridge $br_name exist already."
-			continue
-		fi
+if ! ($vsctl show > /dev/null 2>&1); then
+	if [ -n "$ovs_start" ]; then
+		info "Starting $ovs_service"
+		$ovs_start
+	fi
+fi
 
-		missing_port=0
-		ovs_br_ports=""
-		for port in $br_ports
-		do
-			if [ -d /sys/class/net/$port ]; then
-				ovs_br_ports="$ovs_br_ports $port"
-			else
-				info "port device $port for bridge $br_name is missing."
-				case $port in
-					pf*sf*)
-						info "RDMA functionality is not expected to work without $port in $br_name"
-					;;
-					*)
-						missing_port=$((missing_port+1))
-					;;
-				esac
-			fi
-		done
+ovsbr_number=`$vsctl list-br | wc -l`
+if [ $ovsbr_number -gt 0 ]; then
+	if ($vsctl get Open_vSwitch . Other_config 2> /dev/null | grep 'hw-offload="true"'); then
+		ovs_restart
+	fi
+	exit $RC
+fi
 
-		if [ $missing_port -gt 0 ]; then
-			info "Skipping $br_name configuration."
-			continue
-		fi
+CREATE_OVS_BRIDGES=${CREATE_OVS_BRIDGES:-"yes"}
+if [ "X${CREATE_OVS_BRIDGES}" != "Xyes" ]; then
+	exit $RC
+fi
 
-		$vsctl add-br $br_name
-		info "Created bridge: $br_name"
-		for port in $ovs_br_ports
-		do
-			$vsctl add-port $br_name $port
-			info "bridge $br_name: added port $port"
-		done
+for i in `seq $num_of_devs`
+do
+	br_name=OVS_BRIDGE${i}
+	br_name=${!br_name}
+	br_ports=OVS_BRIDGE${i}_PORTS
+	br_ports=${!br_ports}
 
-		if [ "X${OVS_HW_OFFLOAD}" == "Xyes" ]; then
-			$vsctl set Open_vSwitch . Other_config:hw-offload=true
-			for port in $br_ports
-			do
-				ethtool -K $port hw-tc-offload on
-			done
-			info "OVS HW offload is set"
+	if ($vsctl br-exists $br_name); then
+		info "bridge $br_name exist already."
+		continue
+	fi
+
+	missing_port=0
+	ovs_br_ports=""
+	for port in $br_ports
+	do
+		if [ -d /sys/class/net/$port ]; then
+			ovs_br_ports="$ovs_br_ports $port"
+		else
+			info "port device $port for bridge $br_name is missing."
+			case $port in
+				pf*sf*)
+					info "RDMA functionality is not expected to work without $port in $br_name"
+				;;
+				*)
+					missing_port=$((missing_port+1))
+				;;
+			esac
 		fi
 	done
-} &
+
+	if [ $missing_port -gt 0 ]; then
+		info "Skipping $br_name configuration."
+		continue
+	fi
+
+	$vsctl add-br $br_name
+	info "Created bridge: $br_name"
+	for port in $ovs_br_ports
+	do
+		$vsctl add-port $br_name $port
+		info "bridge $br_name: added port $port"
+	done
+
+done
+
+if [ "X${OVS_HW_OFFLOAD}" == "Xyes" ]; then
+	$vsctl set Open_vSwitch . Other_config:hw-offload=true
+	if [ $? -eq 0 ]; then
+		info "OVS HW offload is set"
+		info "Going to restart $ovs_service to activate hw-offload"
+		ovs_restart
+	fi
+fi
 
 exit $RC
